### ISSUE TITLE
incompatibility with python3

### ISSUE THREAD

**Issue by mdimiceli** [psycofdj/xtdbash#4]
There is an error with python3 :

```bash
Traceback (most recent call last):
  File "/home/mdimiceli/lib/xtdbash/bin/prompt", line 177, in <module>
    l_printer.run()
  File "/home/mdimiceli/lib/xtdbash/bin/prompt", line 163, in run
    self.write_header()
  File "/home/mdimiceli/lib/xtdbash/bin/prompt", line 96, in write_header
    self.write("\n%s " % Printer.ITEMS["header"], Printer.ITEM_COLORS["header"])
  File "/home/mdimiceli/lib/xtdbash/bin/prompt", line 86, in write
    self.m_count += len(p_text.decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
```

The `decode` function is useless with python3 (the strings are already in unicode format)

**Comment by psycofdj** [comment]
ty
